---
title: "Week 1: Discussion"
subtitle: "Plotting Rapa Nui"
author: "Nathalie"
date: 2025-10-3
execute: 
  eval: true
format:
  html:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r}
library(sf) # for vector data (more soon!)
library(stars) # for raster data (more soon!)
library(tmap) # for static and interactive maps
library(here)
```

```{r}
ei_points <- st_read(here("week1", "data", "easter_island", "ei_points.gpkg"))

ei_elev <- read_stars(here("week1","data", "easter_island", "ei_elev.tif"))

ei_borders <- st_read(here("week1","data", "easter_island", "ei_border.gpkg"))

ei_roads <- st_read(here("week1", "data", "easter_island", "ei_roads.gpkg"))
```

```{r}

```

```{r}
# Creating map outline of Rapa Nui
tm_shape(ei_borders) +
  tm_borders()
```

```{r}
tmap_mode(mode = "view")
```

```{r}
# Expanding on tmap
tm_shape(ei_borders) +
  tm_borders(col = "blue") +
  tm_shape(ei_elev) +
  tm_raster(col.scale = tm_scale(values = "parks.arches", fill.legend = tm_legend(title = "Elevation (m)"))) +
  tm_shape(ei_roads) +
  tm_lines() +
  tm_shape(ei_points) +
  tm_symbols(shape = "type",
             shapes = c("volcano" = 24, "cave_entrance" = 14, "peak" = 16),
             size = 0.5) +
  tm_layout()
```
```{r}
# In ggplot
# extract lat & long from geom column 
volcanoes_point <- ei_points %>%
  mutate(lon = unlist(map(ei_points$geom,1)), # longitude = first component (x)
         lat = unlist(map(ei_points$geom,2))) # latitude = second component (y)
```

```{r}
ggplot() +
  # first add Easter Isand borders
  geom_sf(data = ei_borders, color = "#212529") +
  # add elevation raster
  geom_stars(data = ei_elev) +
  scale_fill_distiller(name = "Elevation (m asl)", # legend title with units
                       palette = "RdYlGn",         # red-yellow-green palette (no need to reverse)
                       na.value = "lightblue") +  # set NA color (background ocean)
  # add road vector
  geom_sf(data = ei_roads, color = "#343a40") +
  # add volcano vector
  geom_point(data = volcanoes_point, 
             aes(x = lon, y = lat, 
                 size = elevation), # point size depends on attribute value
             shape = 17,            # triangle
             color = "#22577a") +
  scale_size_continuous(name = "Volcanoes (m asl)") +       # legend title with units
  ggspatial::annotation_north_arrow(location = "br",        # bottom right
                                    which_north = "true") + # point to north pole
  ggspatial::annotation_scale(location = "bl",              # bottom left
                              width_hint = 0.5) +           # proportion of map area the scalebar should occupy
  labs(title = "Easter Island") +
  theme_minimal()
```

